<?php
/**
 * SafetyFlash centralized terms data.
 * THIS IS THE COMPLETE AND CORRECTED VERSION.
 * Contains all terms from view.php, list.php, form.php, settings.php, and log events.
 */

return [
    'languages' => ['fi', 'sv', 'en', 'it', 'el'],

    'terms' => [

        // --- LOKI- JA TAPAHTUMATERMIT ---
        'STATUS_CHANGED' => [
            'fi' => 'Tila muutettu',
            'sv' => 'Status ändrad',
            'en' => 'Status changed',
            'it' => 'Stato modificato',
            'el' => 'Η κατάσταση άλλαξε',
        ],
        'CREATED' => [
            'fi' => 'Luotu',
            'sv' => 'Skapad',
            'en' => 'Created',
            'it' => 'Creato',
            'el' => 'Δημιουργήθηκε',
        ],
        'INFO_REQUESTED' => [
            'fi' => 'Lisätietoa pyydetty',
            'sv' => 'Mer information begärd',
            'en' => 'Information requested',
            'it' => 'Informazioni richieste',
            'el' => 'Ζητήθηκαν πληροφορίες',
        ],
        'COMMENT_ADDED' => [
            'fi' => 'Kommentti lisätty',
            'sv' => 'Kommentar tillagd',
            'en' => 'Comment added',
            'it' => 'Commento aggiunto',
            'el' => 'Προστέθηκε σχόλιο',
        ],
        'SENT_TO_REVIEW' => [
            'fi' => 'Lähetetty tarkistukseen',
            'sv' => 'Skickat för granskning',
            'en' => 'Sent for review',
            'it' => 'Inviato per revisione',
            'el' => 'Εστάλη για έλεγχο',
        ],
        'SENT_TO_COMMS' => [
            'fi' => 'Lähetetty viestintään',
            'sv' => 'Skickat till kommunikation',
            'en' => 'Sent to communications',
            'it' => 'Inviato alla comunicazione',
            'el' => 'Εστάλη στο τμήμα επικοινωνίας',
        ],
        'PUBLISHED' => [
            'fi' => 'Julkaistu',
            'sv' => 'Publicerad',
            'en' => 'Published',
            'it' => 'Pubblicato',
            'el' => 'Δημοσιεύτηκε',
        ],
        'DELETED' => [
            'fi' => 'Poistettu',
            'sv' => 'Borttagen',
            'en' => 'Deleted',
            'it' => 'Eliminato',
            'el' => 'Διαγράφηκε',
        ],
        'notice_logged_in' => [
    'fi' => 'Tervetuloa!  Olet kirjautunut sisään.',
    'sv' => 'Välkommen! Du är nu inloggad.',
    'en' => 'Welcome!  You are now logged in.',
    'it' => 'Benvenuto!  Hai effettuato l\'accesso.',
    'el' => 'Καλώς ήρθατε!  Έχετε συνδεθεί.',
],

// --- VIEW.PHP TUTKINTATIEDOTE KORTIT ---
'card_1_summary' => [
    'fi' => '1. Yhteenveto & kuvat',
    'sv' => '1. Sammanfattning & bilder',
    'en' => '1. Summary & images',
    'it' => '1. Riepilogo & immagini',
    'el' => '1. Σύνοψη & εικόνες',
],

'card_2_investigation' => [
    'fi' => '2. Juurisyyt & toimenpiteet',
    'sv' => '2. Grundorsaker & åtgärder',
    'en' => '2. Root causes & actions',
    'it' => '2. Cause & azioni',
    'el' => '2. Αιτίες & ενέργειες',
],

'card_1' => [
    'fi' => 'Kortti 1',
    'sv' => 'Kort 1',
    'en' => 'Card 1',
    'it' => 'Scheda 1',
    'el' => 'Κάρτα 1',
],

'card_2' => [
    'fi' => 'Kortti 2',
    'sv' => 'Kort 2',
    'en' => 'Card 2',
    'it' => 'Scheda 2',
    'el' => 'Κάρτα 2',
],

'download_card_1' => [
    'fi' => 'Lataa kortti 1',
    'sv' => 'Ladda ner kort 1',
    'en' => 'Download card 1',
    'it' => 'Scarica scheda 1',
    'el' => 'Λήψη κάρτας 1',
],
'no_results_hint' => [
    'fi' => 'Kokeile muuttaa suodattimia tai luo uusi tiedote.',
    'en' => 'Try adjusting your filters or create a new bulletin.',
    'sv' => 'Försök ändra filtren eller skapa ett nytt meddelande.',
    'it' => 'Prova a modificare i filtri o crea un nuovo bollettino.',
    'el' => 'Δοκιμάστε να αλλάξετε τα φίλτρα ή δημιουργήστε ένα νέο δελτίο.',
],
'download_card_2' => [
    'fi' => 'Lataa kortti 2',
    'sv' => 'Ladda ner kort 2',
    'en' => 'Download card 2',
    'it' => 'Scarica scheda 2',
    'el' => 'Λήψη κάρτας 2',
],
// --- LOKITAPAHTUMAT (lisää) ---
'investigation_added' => [
    'fi' => 'Tutkintatiedote lisätty',
    'sv' => 'Utredningsrapport tillagd',
    'en' => 'Investigation report added',
    'it' => 'Rapporto di indagine aggiunto',
    'el' => 'Προστέθηκε έκθεση έρευνας',
],

'type_changed' => [
    'fi' => 'Tyyppi muutettu',
    'sv' => 'Typ ändrad',
    'en' => 'Type changed',
    'it' => 'Tipo modificato',
    'el' => 'Ο τύπος άλλαξε',
],
'preview_2_not_generated' => [
    'fi' => 'Kortin 2 esikatselukuvaa ei ole vielä generoitu.',
    'sv' => 'Kort 2:s förhandsvisning har inte genererats ännu.',
    'en' => 'Card 2 preview has not been generated yet.',
    'it' => 'L\'anteprima della scheda 2 non è ancora stata generata.',
    'el' => 'Η προεπισκόπηση της κάρτας 2 δεν έχει δημιουργηθεί ακόμα.',
],

'root_causes_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Grundorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],

        // --- YLEISET ---
'actions_label' => [
    'fi' => 'Toimenpiteet',
    'sv' => 'Åtgärder',
    'en' => 'Corrective actions',
    'it' => 'Azioni correttive',
    'el' => 'Διορθωτικές ενέργειες',
],
        'back_to_list' => [
            'fi' => 'Takaisin listaukseen',
            'sv' => 'Tillbaka till listan',
            'en' => 'Back to list',
            'it' => 'Torna alla lista',
            'el' => 'Πίσω στη λίστα',
        ],
        'btn_add' => [
            'fi' => 'Lisää',
            'sv' => 'Lägg till',
            'en' => 'Add',
            'it' => 'Aggiungi',
            'el' => 'Προσθήκη',
        ],
        'btn_cancel' => [
            'fi' => 'Peruuta',
            'sv' => 'Avbryt',
            'en' => 'Cancel',
            'it' => 'Annulla',
            'el' => 'Άκυρο',
        ],
        'btn_delete' => [
            'fi' => 'Poista',
            'sv' => 'Ta bort',
            'en' => 'Delete',
            'it' => 'Elimina',
            'el' => 'Διαγραφή',
        ],
        'btn_next' => [
            'fi' => 'Seuraava',
            'sv' => 'Nästa',
            'en' => 'Next',
            'it' => 'Avanti',
            'el' => 'Επόμενο',
        ],
        'btn_prev' => [
            'fi' => 'Edellinen',
            'sv' => 'Föregående',
            'en' => 'Previous',
            'it' => 'Indietro',
            'el' => 'Προηγούμενο',
        ],
        'btn_publish' => [
            'fi' => 'Julkaise',
            'sv' => 'Publicera',
            'en' => 'Publish',
            'it' => 'Pubblica',
            'el' => 'Δημοσίευση',
        ],
        'btn_save' => [
            'fi' => 'Tallenna',
            'sv' => 'Spara',
            'en' => 'Save',
            'it' => 'Salva',
            'el' => 'Αποθήκευση',
        ],
        'btn_save_draft' => [
            'fi' => 'Tallenna luonnos',
            'sv' => 'Spara utkast',
            'en' => 'Save draft',
            'it' => 'Salva bozza',
            'el' => 'Αποθήκευση πρόχειρου',
        ],
        'btn_send_review' => [
            'fi' => 'Lähetä tarkistettavaksi',
            'sv' => 'Skicka för granskning',
            'en' => 'Send for Review',
            'it' => 'Invia per revisione',
            'el' => 'Αποστολή για έλεγχο',
        ],
'dangerous_situation' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
        'description_label' => [
            'fi' => 'Kuvaus',
            'sv' => 'Beskrivning',
            'en' => 'Description',
            'it' => 'Descrizione',
            'el' => 'Περιγραφή',
        ],
'first_release' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First release',
    'it' => 'Primo rilascio',
    'el' => 'Πρώτη δημοσίευση',
],
'investigation_report' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsrapport',
    'en' => 'Investigation report',
    'it' => 'Rilascio dopo l\'indagine',
    'el' => 'Έκθεση έρευνας',
],
'root_cause_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Rotorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],
        'short_title_label' => [
            'fi' => 'Lyhyt kuvaus',
            'sv' => 'Kort rubrik',
            'en' => 'Short description',
            'it' => 'Titolo breve',
            'el' => 'Σύντομος τίτλος',
        ],
        'site_label' => [
            'fi' => 'Työmaa',
            'sv' => 'Arbetsplats',
            'en' => 'Worksite',
            'it' => 'Cantiere',
            'el' => 'Εργοτάξιο',
        ],
        'when_label' => [
            'fi' => 'Milloin?',
            'sv' => 'När?',
            'en' => 'When?',
            'it' => 'Quando?',
            'el' => 'Πότε;',
        ],

        // --- LIST.PHP ---
        'list_heading' => [
            'fi' => 'Safetyflash-lista',
            'sv' => 'Safetyflash-lista',
            'en' => 'Safetyflash list',
            'it' => 'Lista Safetyflash',
            'el' => 'Λίστα Safetyflash',
        ],
        'filter_all' => [
            'fi' => 'Kaikki',
            'sv' => 'Alla',
            'en' => 'All',
            'it' => 'Tutti',
            'el' => 'Όλα',
        ],
        'filter_apply' => [
            'fi' => 'Käytä suodattimia',
            'sv' => 'Använd filter',
            'en' => 'Apply filters',
            'it' => 'Applica filtri',
            'el' => 'Εφαρμογή φίλτρων',
        ],
        'filter_clear' => [
            'fi' => 'Tyhjennä suodattimet',
            'sv' => 'Rensa filter',
            'en' => 'Clear filters',
            'it' => 'Pulisci filtri',
            'el' => 'Καθαρισμός φίλτρων',
        ],
        'filter_date_from' => [
            'fi' => 'Alkaen',
            'sv' => 'Från',
            'en' => 'From',
            'it' => 'Da',
            'el' => 'Από',
        ],
        'filter_date_to' => [
            'fi' => 'Päättyen',
            'sv' => 'Till',
            'en' => 'To',
            'it' => 'A',
            'el' => 'Έως',
        ],
        'filter_search_label' => [
            'fi' => 'Vapaa sanahaku',
            'sv' => 'Fritextsökning',
            'en' => 'Free text search',
            'it' => 'Ricerca libera',
            'el' => 'Αναζήτηση ελεύθερου κειμένου',
        ],
        'filter_search_placeholder' => [
            'fi' => 'Hae otsikosta, kuvauksesta...',
            'sv' => 'Sök i rubrik, beskrivning...',
            'en' => 'Search in title, description...',
            'it' => 'Cerca nel titolo, descrizione...',
            'el' => 'Αναζήτηση σε τίτλο, περιγραφή...',
        ],
        'filter_site' => [
            'fi' => 'Työmaa',
            'sv' => 'Arbetsplats',
            'en' => 'Worksite',
            'it' => 'Cantiere',
            'el' => 'Εργοτάξιο',
        ],
        'filter_state' => [
            'fi' => 'Tila',
            'sv' => 'Status',
            'en' => 'Status',
            'it' => 'Stato',
            'el' => 'Κατάσταση',
        ],
        'filter_type' => [
            'fi' => 'Tyyppi',
            'sv' => 'Typ',
            'en' => 'Type',
            'it' => 'Tipo',
            'el' => 'Τύπος',
        ],
        'card_modified' => [
            'fi' => 'viimeksi muokattu',
            'sv' => 'senast ändrad',
            'en' => 'last modified',
            'it' => 'ultima modifica',
            'el' => 'τελευταία τροποποίηση',
        ],
        'card_open' => [
            'fi' => 'Avaa',
            'sv' => 'Öppna',
            'en' => 'Open',
            'it' => 'Apri',
            'el' => 'Άνοιγμα',
        ],
'no_results' => [
    'fi' => 'Ei tuloksia valituilla suodattimilla.',
    'sv' => 'Inga resultat med de valda filtren.',
    'en' => 'No results for the selected filters.',
    'it' => 'Nessun risultato con i filtri selezionati.',
    'el' => 'Δεν υπάρχουν αποτελέσματα για τα επιλεγμένα φίλτρα.',
],

        // --- VIEW.PHP ---
        'view_status' => [
            'fi' => 'Tila',
            'sv' => 'Status',
            'en' => 'Status',
            'it' => 'Stato',
            'el' => 'Κατάσταση',
        ],
        'view_details_heading' => [
            'fi' => 'Safetyflash-tiedot',
            'sv' => 'Information om Safetyflash',
            'en' => 'Safetyflash details',
            'it' => 'Dettagli Safetyflash',
            'el' => 'Λεπτομέρειες Safetyflash',
        ],
        'view_languages_aria' => [
            'fi' => 'Kielet',
            'sv' => 'Språk',
            'en' => 'Languages',
            'it' => 'Lingue',
            'el' => 'Γλώσσες',
        ],
        'meta_title_internal' => [
            'fi' => 'Otsikko (vain järjestelmää varten)',
            'sv' => 'Rubrik (endast för systemet)',
            'en' => 'Title (system only)',
            'it' => 'Titolo (solo per il sistema)',
            'el' => 'Τίτλος (μόνο για το σύστημα)',
        ],
        'meta_summary_short' => [
            'fi' => 'Lyhyt yhteenveto',
            'sv' => 'Kort sammanfattning',
            'en' => 'Short summary',
            'it' => 'Breve sommario',
            'el' => 'Σύντομη σύνοψη',
        ],
        'meta_description_long' => [
            'fi' => 'Pitkä kuvaus',
            'sv' => 'Lång beskrivning',
            'en' => 'Long description',
            'it' => 'Descrizione estesa',
            'el' => 'Εκτενής περιγραφή',
        ],
        'meta_type' => [
            'fi' => 'Tyyppi',
            'sv' => 'Typ',
            'en' => 'Type',
            'it' => 'Tipo',
            'el' => 'Τύπος',
        ],
        'meta_site' => [
            'fi' => 'Työmaa',
            'sv' => 'Arbetsplats',
            'en' => 'Worksite',
            'it' => 'Cantiere',
            'el' => 'Εργοτάξιο',
        ],
        'meta_occurred_at' => [
            'fi' => 'Tapahtuma-aika',
            'sv' => 'Tidpunkt',
            'en' => 'Time of incident',
            'it' => 'Data/ora evento',
            'el' => 'Χρόνος συμβάντος',
        ],
        'meta_system_heading' => [
            'fi' => 'Järjestelmätiedot',
            'sv' => 'Systeminformation',
            'en' => 'System information',
            'it' => 'Informazioni di sistema',
            'el' => 'Πληροφορίες συστήματος',
        ],
        'meta_language' => [
            'fi' => 'Kieli',
            'sv' => 'Språk',
            'en' => 'Language',
            'it' => 'Lingua',
            'el' => 'Γλώσσα',
        ],
        'meta_created_at' => [
            'fi' => 'Luotu',
            'sv' => 'Skapad',
            'en' => 'Created',
            'it' => 'Creato',
            'el' => 'Δημιουργήθηκε',
        ],
        'meta_updated_at' => [
            'fi' => 'Viimeksi muokattu',
            'sv' => 'Senast ändrad',
            'en' => 'Last modified',
            'it' => 'Ultima modifica',
            'el' => 'Τροποποιήθηκε τελευταία',
        ],
        'log_title' => [
            'fi' => 'Lokitiedot',
            'sv' => 'Logg',
            'en' => 'Log',
            'it' => 'Log',
            'el' => 'Καταγραφή',
        ],
        'log_empty' => [
            'fi' => 'Ei lokitietoja.',
            'sv' => 'Inga loggposter.',
            'en' => 'No log entries.',
            'it' => 'Nessuna voce di log.',
            'el' => 'Δεν υπάρχουν καταχωρήσεις καταγραφής.',
        ],
        'log_show_more' => [
            'fi' => 'Näytä lisää',
            'sv' => 'Visa mer',
            'en' => 'Show more',
            'it' => 'Mostra di più',
            'el' => 'Εμφάνιση περισσότερων',
        ],
        'log_show_less' => [
            'fi' => 'Näytä vähemmän',
            'sv' => 'Visa mindre',
            'en' => 'Show less',
            'it' => 'Mostra meno',
            'el' => 'Εμφάνιση λιγότερων',
        ],
        'log_system_user' => [
            'fi' => 'Järjestelmä',
            'sv' => 'System',
            'en' => 'System',
            'it' => 'Sistema',
            'el' => 'Σύστημα',
        ],

        // --- VIEW.PHP MODALS ---
        'modal_edit_title' => [
            'fi' => 'Muokkaa tiedotetta',
            'sv' => 'Redigera meddelande',
            'en' => 'Edit flash',
            'it' => 'Modifica comunicazione',
            'el' => 'Επεξεργασία ανακοίνωσης',
        ],
        'modal_edit_text' => [
            'fi' => 'Siirryt muokkaamaan tätä tiedotetta.',
            'sv' => 'Du går vidare till redigering av detta meddelande.',
            'en' => 'You will proceed to edit this flash.',
            'it' => 'Procederai alla modifica di questa comunicazione.',
            'el' => 'Θα μεταβείς στην επεξεργασία αυτής της ανακοίνωσης.',
        ],
        'btn_ok_edit' => [
            'fi' => 'Siirry muokkaamaan',
            'sv' => 'Gå till redigering',
            'en' => 'Go to edit',
            'it' => 'Vai a modifica',
            'el' => 'Μετάβαση σε επεξεργασία',
        ],
        'modal_comment_title' => [
            'fi' => 'Lisää kommentti',
            'sv' => 'Lägg till kommentar',
            'en' => 'Add comment',
            'it' => 'Aggiungi commento',
            'el' => 'Προσθήκη σχολίου',
        ],
        'modal_comment_label' => [
            'fi' => 'Kommentti',
            'sv' => 'Kommentar',
            'en' => 'Comment',
            'it' => 'Commento',
            'el' => 'Σχόλιο',
        ],
        'modal_comment_placeholder' => [
            'fi' => 'Kirjoita kommenttisi tähän',
            'sv' => 'Skriv din kommentar här',
            'en' => 'Write your comment here',
            'it' => 'Scrivi qui il tuo commento',
            'el' => 'Γράψτε εδώ το σχόλιό σας',
        ],
        'btn_comment_send' => [
            'fi' => 'Lähetä kommentti',
            'sv' => 'Skicka kommentar',
            'en' => 'Send comment',
            'it' => 'Invia commento',
            'el' => 'Αποστολή σχολίου',
        ],
        'modal_request_title' => [
            'fi' => 'Palauta korjattavaksi',
            'sv' => 'Skicka tillbaka för korrigering',
            'en' => 'Return for corrections',
            'it' => 'Rimanda per correzioni',
            'el' => 'Επιστροφή για διόρθωση',
        ],
        'modal_request_label' => [
            'fi' => 'Palautteen syy',
            'sv' => 'Anledning till återkoppling',
            'en' => 'Reason for feedback',
            'it' => 'Motivo del feedback',
            'el' => 'Λόγος ανατροφοδότησης',
        ],
        'modal_request_placeholder' => [
            'fi' => 'Kerro tarkasti, mitä tulee korjata tai täydentää.',
            'sv' => 'Beskriv tydligt vad som ska korrigeras eller kompletteras.',
            'en' => 'Describe exactly what needs to be corrected or completed.',
            'it' => 'Descrivi esattamente cosa deve essere corretto o completato.',
            'el' => 'Περιγράψτε με ακρίβεια τι πρέπει να διορθωθεί ή να συμπληρωθεί.',
        ],
        'btn_send_request' => [
            'fi' => 'Pyydä lisätietoja',
            'sv' => 'Begär mer information',
            'en' => 'Request more information',
            'it' => 'Richiedi ulteriori informazioni',
            'el' => 'Ζήτα περισσότερες πληροφορίες',
        ],
        'modal_to_comms_title' => [
            'fi' => 'Lähetä viestintään',
            'sv' => 'Skicka till kommunikation',
            'en' => 'Send to communications',
            'it' => 'Invia alla comunicazione',
            'el' => 'Αποστολή στο τμήμα επικοινωνίας',
        ],
        'modal_to_comms_label' => [
            'fi' => 'Viesti viestinnälle',
            'sv' => 'Meddelande till kommunikation',
            'en' => 'Message to communications',
            'it' => 'Messaggio alla comunicazione',
            'el' => 'Μήνυμα προς το τμήμα επικοινωνίας',
        ],
        'modal_to_comms_placeholder' => [
            'fi' => 'Kuvaile, mitä viestinnän tulisi tehdä tämän tiedotteen kanssa',
            'sv' => 'Beskriv vad kommunikationen ska göra med detta meddelande',
            'en' => 'Describe what communications should do with this flash',
            'it' => 'Descrivi cosa dovrebbe fare la comunicazione con questa comunicazione',
            'el' => 'Περιγράψτε τι πρέπει να κάνει το τμήμα επικοινωνίας με αυτή την ανακοίνωση',
        ],
        'btn_send_comms' => [
            'fi' => 'Lähetä viestintään',
            'sv' => 'Skicka till kommunikation',
            'en' => 'Send to communications',
            'it' => 'Invia alla comunicazione',
            'el' => 'Αποστολή στο τμήμα επικοινωνίας',
        ],
        'modal_publish_title' => [
            'fi' => 'Julkaise tiedote',
            'sv' => 'Publicera meddelande',
            'en' => 'Publish flash',
            'it' => 'Pubblica comunicazione',
            'el' => 'Δημοσίευση ανακοίνωσης',
        ],
        'modal_publish_text' => [
            'fi' => 'Haluatko julkaista tämän tiedotteen? Tiedote lähtee Safetyflash käyttäjäryhmälle',
            'sv' => 'Vill du publicera detta meddelande på skärmarna?',
            'en' => 'Do you want to publish this flash to the screens?',
            'it' => 'Vuoi pubblicare questa comunicazione sugli schermi?',
            'el' => 'Θέλεις να δημοσιεύσεις αυτή την ανακοίνωση στις οθόνες;',
        ],
        'modal_delete_title' => [
            'fi' => 'Poista tiedote',
            'sv' => 'Ta bort meddelande',
            'en' => 'Delete flash',
            'it' => 'Elimina comunicazione',
            'el' => 'Διαγραφή ανακοίνωσης',
        ],
        'modal_delete_text' => [
            'fi' => 'Haluatko varmasti poistaa tämän tiedotteen?',
            'sv' => 'Vill du verkligen ta bort detta meddelande?',
            'en' => 'Are you sure you want to delete this flash?',
            'it' => 'Vuoi davvero eliminare questa comunicazione?',
            'el' => 'Είσαι βέβαιος ότι θέλεις να διαγράψεις αυτή την ανακοίνωση;',
        ],

        // --- VIEW.PHP FOOTER ---
        'footer_edit' => [
            'fi' => 'Muokkaa',
            'sv' => 'Redigera',
            'en' => 'Edit',
            'it' => 'Modifica',
            'el' => 'Επεξεργασία',
        ],
        'footer_comment' => [
            'fi' => 'Lisää kommentti',
            'sv' => 'Lägg till kommentar',
            'en' => 'Add comment',
            'it' => 'Aggiungi commento',
            'el' => 'Προσθήκη σχολίου',
        ],
        'footer_return' => [
            'fi' => 'Palauta korjattavaksi',
            'sv' => 'Skicka tillbaka för korrigering',
            'en' => 'Return for corrections',
            'it' => 'Rimanda per correzioni',
            'el' => 'Επιστροφή για διόρθωση',
        ],
        'footer_to_comms' => [
            'fi' => 'Lähetä viestintään',
            'sv' => 'Skicka till kommunikation',
            'en' => 'Send to communications',
            'it' => 'Invia alla comunicazione',
            'el' => 'Αποστολή στο τμήμα επικοινωνίας',
        ],
        'footer_delete' => [
            'fi' => 'Poista',
            'sv' => 'Ta bort',
            'en' => 'Delete',
            'it' => 'Elimina',
            'el' => 'Διαγραφή',
        ],
        'footer_publish' => [
            'fi' => 'Julkaise',
            'sv' => 'Publicera',
            'en' => 'Publish',
            'it' => 'Pubblica',
            'el' => 'Δημοσίευση',
        ],
        'footer_send_to_review' => [
            'fi' => 'Lähetä tarkistettavaksi',
            'sv' => 'Skicka för granskning',
            'en' => 'Send for review',
            'it' => 'Invia per revisione',
            'el' => 'Αποστολή για έλεγχο',
        ],

        // --- FORM.PHP ---
        'step1_heading' => [
            'fi' => '1. Valitse tiedotteen tyyppi',
            'sv' => '1. Välj meddelandetyp',
            'en' => '1. Choose flash type',
            'it' => '1. Scegli il tipo di comunicazione',
            'el' => '1. Επιλέξτε τύπο ανακοίνωσης',
        ],
        'step2_heading' => [
            'fi' => '2. Konteksti',
            'sv' => '2. Kontext',
            'en' => '2. Context',
            'it' => '2. Contesto',
            'el' => '2. Πλαίσιο',
        ],
        'step3_heading' => [
            'fi' => '3. Sisältö',
            'sv' => '3. Innehåll',
            'en' => '3. Content',
            'it' => '3. Contenuto',
            'el' => '3. Περιεχόμενο',
        ],
        'step4_heading' => [
            'fi' => '4. Kuvat',
            'sv' => '4. Bilder',
            'en' => '4. Images',
            'it' => '4. Immagini',
            'el' => '4. Εικόνες',
        ],
        'step4_help' => [
            'fi' => 'Lataa vähintään yksi kuva. Voit säätää kuvien paikkaa ja zoomia seuraavassa vaiheessa.',
            'sv' => 'Ladda upp minst en bild. Du kan justera bildernas position och zoom i nästa steg.',
            'en' => 'Upload at least one image. You can adjust the position and zoom in the next step.',
            'it' => 'Carica almeno un\'immagine. Puoi regolare posizione e zoom nel passaggio successivo.',
            'el' => 'Ανεβάστε τουλάχιστον μία εικόνα. Μπορείτε να ρυθμίσετε τη θέση και το ζουμ στο επόμενο βήμα.',
        ],
        'img_main_label' => [
            'fi' => 'Pääkuva',
            'sv' => 'Huvudbild',
            'en' => 'Main image',
            'it' => 'Immagine principale',
            'el' => 'Κύρια εικόνα',
        ],
        'img_2_label' => [
            'fi' => 'Lisäkuva 1',
            'sv' => 'Extrabild 1',
            'en' => 'Extra image 1',
            'it' => 'Immagine extra 1',
            'el' => 'Επιπλέον εικόνα 1',
        ],
        'img_3_label' => [
            'fi' => 'Lisäkuva 2',
            'sv' => 'Extrabild 2',
            'en' => 'Extra image 2',
            'it' => 'Immagine extra 2',
            'el' => 'Επιπλέον εικόνα 2',
        ],
        'layout_label' => [
            'fi' => 'Kuvien asettelu',
            'sv' => 'Bildlayout',
            'en' => 'Image layout',
            'it' => 'Disposizione immagini',
            'el' => 'Διάταξη εικόνων',
        ],
        'layout_auto' => [
            'fi' => 'Valitse asettelu automaattisesti',
            'sv' => 'Välj layout automatiskt',
            'en' => 'Choose layout automatically',
            'it' => 'Scegli layout automaticamente',
            'el' => 'Επιλογή διάταξης αυτόματα',
        ],
        'layout_main_only' => [
            'fi' => 'Vain pääkuva',
            'sv' => 'Endast huvudbild',
            'en' => 'Main image only',
            'it' => 'Solo immagine principale',
            'el' => 'Μόνο κύρια εικόνα',
        ],
        'layout_two_main_large' => [
            'fi' => 'Pääkuva ylhäällä, lisäkuva alla',
            'sv' => 'Huvudbild överst, extrabild under',
            'en' => 'Main image on top, secondary below',
            'it' => 'Immagine principale in alto, secondaria sotto',
            'el' => 'Κύρια εικόνα επάνω, δευτερεύουσα από κάτω',
        ],
        'layout_two_even' => [
            'fi' => 'Kaksi kuvaa vierekkäin',
            'sv' => 'Två bilder bredvid varandra',
            'en' => 'Two images side by side',
            'it' => 'Due immagini affiancate',
            'el' => 'Δύο εικόνες δίπλα δίπλα',
        ],
        'layout_three_main' => [
            'fi' => 'Pääkuva + kaksi pienempää',
            'sv' => 'Huvudbild + två mindre',
            'en' => 'Main + two smaller images',
            'it' => 'Principale + due più piccole',
            'el' => 'Κύρια + δύο μικρότερες',
        ],
        'layout_three_even' => [
            'fi' => 'Kolme kuvaa tasajakona',
            'sv' => 'Tre bilder i jämn fördelning',
            'en' => 'Three images, even layout',
            'it' => 'Tre immagini in layout uniforme',
            'el' => 'Τρεις εικόνες σε ομοιόμορφη διάταξη',
        ],
        'layout_three_overlay' => [
            'fi' => 'Pääkuva, pikkukuvat kulmassa',
            'sv' => 'Huvudbild med miniatyrer i hörnet',
            'en' => 'Main image with thumbnails in the corner',
            'it' => 'Principale con miniature nell’angolo',
            'el' => 'Κύρια εικόνα με μικρογραφίες στη γωνία',
        ],
'slider_help' => [
    'fi' => 'Klikkaa pääkuvaa tai pikkukuvaa ja säädä sen sijaintia sekä zoomia.',
    'sv' => 'Klicka på huvudbilden eller miniatyrbilden och justera dess position och zoom.',
    'en' => 'Click the main image or thumbnail and adjust its position and zoom.',
    'it' => 'Clicca sull\'immagine principale o sulla miniatura e regola la sua posizione e zoom.',
    'el' => 'Κάντε κλικ στην κύρια εικόνα ή τη μικρογραφία και ρυθμίστε τη θέση και το ζουμ της.',
],
'slider_zoom_label' => [
    'fi' => 'Zoom',
    'sv' => 'Zoom',
    'en' => 'Zoom',
    'it' => 'Zoom',
    'el' => 'Ζουμ',
],
'slider_position_x_label' => [
    'fi' => 'Sijainti X',
    'sv' => 'Position X',
    'en' => 'Position X',
    'it' => 'Posizione X',
    'el' => 'Θέση X',
],
'slider_position_y_label' => [
    'fi' => 'Sijainti Y',
    'sv' => 'Position Y',
    'en' => 'Position Y',
    'it' => 'Posizione Y',
    'el' => 'Θέση Y',
],
'slider_reset' => [
    'fi' => 'Palauta oletukset',
    'sv' => 'Återställ standardvärden',
    'en' => 'Reset to defaults',
    'it' => 'Ripristina predefiniti',
    'el' => 'Επαναφορά προεπιλογών',
],
'image_selected' => [
    'fi' => 'Kuva valittu',
    'sv' => 'Bild vald',
    'en' => 'Image selected',
    'it' => 'Immagine selezionata',
    'el' => 'Επιλέχθηκε εικόνα',
],
'click_image_to_edit' => [
    'fi' => 'Klikkaa kuvaa muokataksesi',
    'sv' => 'Klicka på bilden för att redigera',
    'en' => 'Click image to edit',
    'it' => 'Clicca sull\'immagine per modificare',
    'el' => 'Κάντε κλικ στην εικόνα για επεξεργασία',
],

        // --- ASETUKSET ---
        'settings_heading' => [
            'fi' => 'Asetukset',
            'sv' => 'Inställningar',
            'en' => 'Settings',
            'it' => 'Impostazioni',
            'el' => 'Ρυθμίσεις',
        ],
        'settings_tab_users' => [
            'fi' => 'Käyttäjät',
            'sv' => 'Användare',
            'en' => 'Users',
            'it' => 'Utenti',
            'el' => 'Χρήστες',
        ],
        'settings_tab_worksites' => [
            'fi' => 'Työmaat',
            'sv' => 'Arbetsplatser',
            'en' => 'Worksites',
            'it' => 'Cantieri',
            'el' => 'Εργοτάξια',
        ],
        'settings_worksites_heading' => [
            'fi' => 'Työmaiden hallinta',
            'sv' => 'Hantering av arbetsplatser',
            'en' => 'Worksite management',
            'it' => 'Gestione cantieri',
            'el' => 'Διαχείριση εργοταξίων',
        ],
        'settings_worksites_add_label' => [
            'fi' => 'Uusi työmaa:',
            'sv' => 'Ny arbetsplats:',
            'en' => 'New worksite:',
            'it' => 'Nuovo cantiere:',
            'el' => 'Νέο εργοτάξιο:',
        ],
        'settings_worksites_col_name' => [
            'fi' => 'Nimi',
            'sv' => 'Namn',
            'en' => 'Name',
            'it' => 'Nome',
            'el' => 'Όνομα',
        ],
        'settings_worksites_col_active' => [
            'fi' => 'Aktiivinen',
            'sv' => 'Aktiv',
            'en' => 'Active',
            'it' => 'Attivo',
            'el' => 'Ενεργό',
        ],
        'settings_worksites_col_actions' => [
            'fi' => 'Toiminnot',
            'sv' => 'Åtgärder',
            'en' => 'Actions',
            'it' => 'Azioni',
            'el' => 'Ενέργειες',
        ],
        'settings_worksites_action_disable' => [
            'fi' => 'Passivoi',
            'sv' => 'Inaktivera',
            'en' => 'Deactivate',
            'it' => 'Disattiva',
            'el' => 'Απενεργοποίηση',
        ],
        'settings_worksites_action_enable' => [
            'fi' => 'Aktivoi',
            'sv' => 'Aktivera',
            'en' => 'Activate',
            'it' => 'Attiva',
            'el' => 'Ενεργοποίηση',
        ],
        'users_heading' => [
            'fi' => 'Käyttäjien hallinta',
            'sv' => 'Användarhantering',
            'en' => 'User management',
            'it' => 'Gestione utenti',
            'el' => 'Διαχείριση χρηστών',
        ],
        'users_add_button' => [
            'fi' => 'Lisää käyttäjä',
            'sv' => 'Lägg till användare',
            'en' => 'Add user',
            'it' => 'Aggiungi utente',
            'el' => 'Προσθήκη χρήστη',
        ],
        'users_col_name' => [
            'fi' => 'Nimi',
            'sv' => 'Namn',
            'en' => 'Name',
            'it' => 'Nome',
            'el' => 'Όνομα',
        ],
        'users_col_email' => [
            'fi' => 'Sähköposti',
            'sv' => 'E-post',
            'en' => 'Email',
            'it' => 'Email',
            'el' => 'Email',
        ],
        'users_col_role' => [
            'fi' => 'Rooli',
            'sv' => 'Roll',
            'en' => 'Role',
            'it' => 'Ruolo',
            'el' => 'Ρόλος',
        ],
        'users_col_home_worksite' => [
            'fi' => 'Kotityömaa',
            'sv' => 'Hemmearbetsplats',
            'en' => 'Home worksite',
            'it' => 'Cantiere principale',
            'el' => 'Κύριο εργοτάξιο',
        ],
        'users_col_created' => [
            'fi' => 'Luotu',
            'sv' => 'Skapad',
            'en' => 'Created',
            'it' => 'Creato',
            'el' => 'Δημιουργήθηκε',
        ],
        'users_col_actions' => [
            'fi' => 'Toiminnot',
            'sv' => 'Åtgärder',
            'en' => 'Actions',
            'it' => 'Azioni',
            'el' => 'Ενέργειες',
        ],
        'users_home_worksite_none' => [
            'fi' => 'Ei määritelty',
            'sv' => 'Ej angiven',
            'en' => 'Not set',
            'it' => 'Non impostato',
            'el' => 'Δεν έχει οριστεί',
        ],
        'users_action_edit' => [
            'fi' => 'Muokkaa',
            'sv' => 'Redigera',
            'en' => 'Edit',
            'it' => 'Modifica',
            'el' => 'Επεξεργασία',
        ],
        'users_action_reset_pass' => [
            'fi' => 'Nollaa salasana',
            'sv' => 'Återställ lösenord',
            'en' => 'Reset password',
            'it' => 'Reimposta password',
            'el' => 'Επαναφορά κωδικού',
        ],
        'users_action_delete' => [
            'fi' => 'Poista',
            'sv' => 'Ta bort',
            'en' => 'Delete',
            'it' => 'Elimina',
            'el' => 'Διαγραφή',
        ],
        'users_modal_add_title' => [
            'fi' => 'Lisää uusi käyttäjä',
            'sv' => 'Lägg till ny användare',
            'en' => 'Add new user',
            'it' => 'Aggiungi nuovo utente',
            'el' => 'Προσθήκη νέου χρήστη',
        ],
        'users_label_first_name' => [
            'fi' => 'Etunimi',
            'sv' => 'Förnamn',
            'en' => 'First name',
            'it' => 'Nome',
            'el' => 'Όνομα',
        ],
        'users_label_last_name' => [
            'fi' => 'Sukunimi',
            'sv' => 'Efternamn',
            'en' => 'Last name',
            'it' => 'Cognome',
            'el' => 'Επώνυμο',
        ],
        'users_label_email' => [
            'fi' => 'Sähköposti',
            'sv' => 'E-post',
            'en' => 'Email',
            'it' => 'Email',
            'el' => 'Email',
        ],
        'users_label_role' => [
            'fi' => 'Rooli',
            'sv' => 'Roll',
            'en' => 'Role',
            'it' => 'Ruolo',
            'el' => 'Ρόλος',
        ],
        'users_label_home_worksite' => [
            'fi' => 'Kotityömaa',
            'sv' => 'Hemmearbetsplats',
            'en' => 'Home worksite',
            'it' => 'Cantiere principale',
            'el' => 'Κύριο εργοτάξιο',
        ],
        'users_label_password_new' => [
            'fi' => 'Uusi salasana (jätä tyhjäksi, jos ei muuteta)',
            'sv' => 'Nytt lösenord (lämna tomt om ingen ändring)',
            'en' => 'New password (leave blank if no change)',
            'it' => 'Nuova password (lasciare vuoto se non si modifica)',
            'el' => 'Νέος κωδικός (αφήστε κενό αν δεν αλλάξει)',
        ],
        'users_delete_title' => [
            'fi' => 'Vahvista poisto',
            'sv' => 'Bekräfta borttagning',
            'en' => 'Confirm deletion',
            'it' => 'Conferma eliminazione',
            'el' => 'Επιβεβαίωση διαγραφής',
        ],
        'users_delete_text' => [
            'fi' => 'Haluatko varmasti poistaa käyttäjän',
            'sv' => 'Är du säker på att du vill ta bort användaren',
            'en' => 'Are you sure you want to delete user',
            'it' => 'Sei sicuro di voler eliminare l\'utente',
            'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τον χρήστη',
        ],
        'users_reset_title' => [
            'fi' => 'Salasanan nollaus',
            'sv' => 'Återställning av lösenord',
            'en' => 'Password reset',
            'it' => 'Reimpostazione password',
            'el' => 'Επαναφορά κωδικού',
        ],
        'users_reset_text_prefix' => [
            'fi' => 'Uusi salasana lähetetään osoitteeseen',
            'sv' => 'Nytt lösenord skickas till',
            'en' => 'A new password will be sent to',
            'it' => 'Una nuova password verrà inviata a',
            'el' => 'Ένας νέος κωδικός θα σταλεί στη διεύθυνση',
        ],
        'users_reset_text_suffix' => [
            'fi' => '. Haluatko jatkaa?',
            'sv' => '. Vill du fortsätta?',
            'en' => '. Do you want to continue?',
            'it' => '. Vuoi continuare?',
            'el' => '. Θέλετε να συνεχίσετε;',
        ],
        'worksite_inactive' => [
            'fi' => 'passivoitu',
            'sv' => 'inaktiv',
            'en' => 'inactive',
            'it' => 'inattivo',
            'el' => 'ανενεργό',
        ],

        // --- ILMOITUKSET ---
        'request_info_banner' => [
            'fi' => 'Vastuuhenkilö on pyytänyt lisätietoja. Täydennä tietoja ja lähetä uudelleen.',
            'sv' => 'Ansvarig har begärt mer information. Komplettera uppgifterna och skicka igen.',
            'en' => 'Responsible person has requested more information. Update the data and resend.',
            'it' => 'Il responsabile ha richiesto ulteriori informazioni. Aggiorna i dati e reinvia.',
            'el' => 'Ο υπεύθυνος ζήτησε περισσότερες πληροφορίες. Ενημερώστε τα στοιχεία και στείλτε ξανά.',
        ],
        'notice_saved' => [
            'fi' => 'Tiedot tallennettu.',
            'sv' => 'Uppgifter sparade.',
            'en' => 'Data saved.',
            'it' => 'Dati salvati.',
            'el' => 'Τα δεδομένα αποθηκεύτηκαν.',
        ],
        'notice_saved_draft' => [
            'fi' => 'Tallennettu luonnokseksi.',
            'sv' => 'Sparat som utkast.',
            'en' => 'Saved as draft.',
            'it' => 'Salvato come bozza.',
            'el' => 'Αποθηκεύτηκε ως πρόχειρο.',
        ],
        'notice_sent_review' => [
            'fi' => 'Lähetetty tarkistettavaksi.',
            'sv' => 'Skickat för granskning.',
            'en' => 'Sent for review.',
            'it' => 'Inviato per revisione.',
            'el' => 'Στάλθηκε για έλεγχο.',
        ],
        'notice_bulk_deleted' => [
    'fi' => 'Poistettu {count} tiedotetta.',
    'sv' => '{count} meddelanden har tagits bort.',
    'en' => '{count} flashes have been deleted.',
    'it' => '{count} comunicazioni sono state eliminate.',
    'el' => '{count} ανακοινώσεις διαγράφηκαν.',
],
        'notice_info_requested' => [
            'fi' => 'Lisätietopyyntö lähetetty.',
            'sv' => 'Begäran om mer information skickad.',
            'en' => 'Request for more information has been sent.',
            'it' => 'Richiesta di ulteriori informazioni inviata.',
            'el' => 'Αίτημα για περισσότερες πληροφορίες εστάλη.',
        ],
        'notice_to_comms' => [
            'fi' => 'Lähetetty viestintään.',
            'sv' => 'Skickat till kommunikation.',
            'en' => 'Sent to communications.',
            'it' => 'Inviato alla comunicazione.',
            'el' => 'Στάλθηκε στο τμήμα επικοινωνίας.',
        ],
        'notice_published' => [
            'fi' => 'Tiedote julkaistu.',
            'sv' => 'Meddelande publicerat.',
            'en' => 'Flash published.',
            'it' => 'Comunicazione pubblicata.',
            'el' => 'Η ανακοίνωση δημοσιεύτηκε.',
        ],
        'notice_deleted' => [
            'fi' => 'Tiedote poistettu.',
            'sv' => 'Meddelandet borttaget.',
            'en' => 'Flash deleted.',
            'it' => 'Comunicazione eliminata.',
            'el' => 'Η ανακοίνωση διαγράφηκε.',
        ],
        'notice_translation_saved' => [
            'fi' => 'Kieliversio tallennettu.',
            'sv' => 'Språkversion sparad.',
            'en' => 'Translation saved.',
            'it' => 'Traduzione salvata.',
            'el' => 'Η μετάφραση αποθηκεύτηκε.',
        ],
        'notice_user_created' => [
            'fi' => 'Käyttäjä luotu.',
            'sv' => 'Användare skapad.',
            'en' => 'User created.',
            'it' => 'Utente creato.',
            'el' => 'Ο χρήστης δημιουργήθηκε.',
        ],
        'notice_user_updated' => [
            'fi' => 'Käyttäjän tiedot päivitetty.',
            'sv' => 'Användaruppgifter uppdaterade.',
            'en' => 'User updated.',
            'it' => 'Utente aggiornato.',
            'el' => 'Τα στοιχεία του χρήστη ενημερώθηκαν.',
        ],
        'notice_user_deleted' => [
            'fi' => 'Käyttäjä poistettu.',
            'sv' => 'Användare borttagen.',
            'en' => 'User deleted.',
            'it' => 'Utente eliminato.',
            'el' => 'Ο χρήστης διαγράφηκε.',
        ],
        'notice_user_pass_reset' => [
            'fi' => 'Salasana nollattu ja uusi salasana lähetetty.',
            'sv' => 'Lösenord återställt och nytt lösenord skickat.',
            'en' => 'Password reset and a new password has been sent.',
            'it' => 'Password reimpostata e nuova password inviata.',
            'el' => 'Ο κωδικός επαναφέρθηκε και στάλθηκε νέος.',
        ],
        'notice_sent' => [
            'fi' => 'Tiedote lähetetty.',
            'sv' => 'Meddelande skickat.',
            'en' => 'Flash sent.',
            'it' => 'Comunicazione inviata.',
            'el' => 'Η ανακοίνωση εστάλη.',
        ],

        // --- NAVIGAATIO ---
        'nav_list' => [
            'fi' => 'Lista',
            'sv' => 'Lista',
            'en' => 'List',
            'it' => 'Lista',
            'el' => 'Λίστα',
        ],
        'nav_new_safetyflash' => [
            'fi' => 'Uusi Safetyflash',
            'sv' => 'Ny Safetyflash',
            'en' => 'New Safetyflash',
            'it' => 'Nuovo Safetyflash',
            'el' => 'Νέο Safetyflash',
        ],
        'nav_logout' => [
            'fi' => 'Kirjaudu ulos',
            'sv' => 'Logga ut',
            'en' => 'Log out',
            'it' => 'Esci',
            'el' => 'Αποσύνδεση',
        ],
                'EDITED' => [
            'fi' => 'Muokattu',
            'sv' => 'Redigerad',
            'en' => 'Edited',
            'it' => 'Modificato',
            'el' => 'Επεξεργάστηκε',
        ],

        // Pienillä kirjaimilla (tietokannasta tulevat)
'created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'edited' => [
    'fi' => 'Muokattu',
    'sv' => 'Redigerad',
    'en' => 'Edited',
    'it' => 'Modificato',
    'el' => 'Επεξεργάστηκε',
],
'status_changed' => [
    'fi' => 'Tila muutettu',
    'sv' => 'Status ändrad',
    'en' => 'Status changed',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'info_requested' => [
    'fi' => 'Lisätietoa pyydetty',
    'sv' => 'Mer information begärd',
    'en' => 'Information requested',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'comment_added' => [
    'fi' => 'Kommentti lisätty',
    'sv' => 'Kommentar tillagd',
    'en' => 'Comment added',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'sent_to_review' => [
    'fi' => 'Lähetetty tarkistukseen',
    'sv' => 'Skickat för granskning',
    'en' => 'Sent for review',
    'it' => 'Inviato per revisione',
    'el' => 'Εστάλη για έλεγχο',
],
'sent_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickat till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Εστάλη στο τμήμα επικοινωνίας',
],
'published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'deleted' => [
    'fi' => 'Poistettu',
    'sv' => 'Borttagen',
    'en' => 'Deleted',
    'it' => 'Eliminato',
    'el' => 'Διαγράφηκε',
],
'download_preview' => [
    'fi' => 'Lataa JPG',
    'sv' => 'Ladda ner JPG',
    'en' => 'Download JPG',
    'it' => 'Scarica JPG',
    'el' => 'Λήψη JPG',
],
// --- FORM.PHP KIELIVALINTA ---
'lang_selection_label' => [
    'fi' => 'Safetyflashin kieli / Language of Safetyflash',
    'sv' => 'Safetyflashens språk / Language of Safetyflash',
    'en' => 'Safetyflash language',
    'it' => 'Lingua del Safetyflash',
    'el' => 'Γλώσσα του Safetyflash',
],
'lang_selection_help' => [
    'fi' => 'Valitse kieli, jolla Safetyflash luodaan.  Käännökset tehdään myöhemmin.',
    'sv' => 'Välj språket för Safetyflash.  Översättningar görs senare.',
    'en' => 'Choose the language for this Safetyflash.  Translations will be done later.',
    'it' => 'Scegli la lingua per questo Safetyflash. Le traduzioni verranno fatte in seguito.',
    'el' => 'Επιλέξτε τη γλώσσα για αυτό το Safetyflash. Οι μεταφράσεις θα γίνουν αργότερα.',
],
'type_selection_label' => [
    'fi' => 'Valitse Safetyflash-tyyppi',
    'sv' => 'Välj Safetyflash-typ',
    'en' => 'Choose Safetyflash type',
    'it' => 'Scegli il tipo di Safetyflash',
    'el' => 'Επιλέξτε τύπο Safetyflash',
],
'type_red_desc' => [
    'fi' => 'Valitse punainen, jos tapahtumaan liittyy henkilövahinko tai -vaara.',
    'sv' => 'Välj röd om händelsen innebär personskada eller fara.',
    'en' => 'Choose red if the incident involves personal injury or danger.',
    'it' => 'Scegli rosso se l\'incidente comporta lesioni personali o pericolo.',
    'el' => 'Επιλέξτε κόκκινο αν το περιστατικό περιλαμβάνει τραυματισμό ή κίνδυνο.',
],
'type_yellow_desc' => [
    'fi' => 'Valitse keltainen, jos kyseessä on laitevaurio.',
    'sv' => 'Välj gul om det gäller utrustningsskada.',
    'en' => 'Choose yellow if it involves equipment damage.',
    'it' => 'Scegli giallo se si tratta di danni alle attrezzature.',
    'el' => 'Επιλέξτε κίτρινο αν αφορά ζημιά εξοπλισμού.',
],
'type_green_desc' => [
    'fi' => 'Valitse vihreä, jos tapahtumaan on tehty tutkinta.',
    'sv' => 'Välj grön om en utredning har genomförts.',
    'en' => 'Choose green if an investigation has been conducted.',
    'it' => 'Scegli verde se è stata condotta un\'indagine.',
    'el' => 'Επιλέξτε πράσινο αν έχει διεξαχθεί έρευνα.',
],
'site_detail_label' => [
    'fi' => 'Tarkempi sijainti',
    'sv' => 'Närmare plats',
    'en' => 'Specific location',
    'it' => 'Posizione specifica',
    'el' => 'Συγκεκριμένη τοποθεσία',
],
'site_detail_placeholder' => [
    'fi' => 'Esim. huoltohalli, murskaamo...',
    'sv' => 'T.ex. servicehall, kross...',
    'en' => 'E.g. maintenance hall, crusher...',
    'it' => 'Es. sala manutenzione, frantoio...',
    'el' => 'Π.χ. αίθουσα συντήρησης, θραυστήρας...',
],
'title_internal_label' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'title_internal_placeholder' => [
    'fi' => 'Esim. Henkilön läheltä piti -tilanne kaivoksella',
    'sv' => 'T.ex. Nära ögat-situation för person vid gruvan',
    'en' => 'E.g. Near miss incident at the mine',
    'it' => 'Es. Quasi incidente alla miniera',
    'el' => 'Π.χ. Παραλίγο ατύχημα στο ορυχείο',
],
'short_text_placeholder' => [
    'fi' => 'Tiivis kuvaus, joka näkyy kortin otsikkona.',
    'sv' => 'Kort beskrivning som visas som kortets rubrik.',
    'en' => 'Brief description shown as the card title.',
    'it' => 'Breve descrizione mostrata come titolo della scheda.',
    'el' => 'Σύντομη περιγραφή που εμφανίζεται ως τίτλος κάρτας.',
],
'description_placeholder' => [
    'fi' => 'Kerro tässä mitä tapahtui ja tämän hetkinen tilanne.',
    'sv' => 'Beskriv här vad som hände och nuläget.',
    'en' => 'Describe what happened and the current situation.',
    'it' => 'Descrivi cosa è successo e la situazione attuale.',
    'el' => 'Περιγράψτε τι συνέβη και την τρέχουσα κατάσταση.',
],
'root_causes_placeholder' => [
    'fi' => '- Juurisyy 1\n- Juurisyy 2',
    'sv' => '- Grundorsak 1\n- Grundorsak 2',
    'en' => '- Root cause 1\n- Root cause 2',
    'it' => '- Causa principale 1\n- Causa principale 2',
    'el' => '- Αιτία 1\n- Αιτία 2',
],
'root_causes_help' => [
    'fi' => 'Kirjaa selkeästi yksi juurisyy kullekin riville.',
    'sv' => 'Skriv tydligt en grundorsak per rad.',
    'en' => 'Write one root cause per line.',
    'it' => 'Scrivi una causa principale per riga.',
    'el' => 'Γράψτε μία αιτία ανά γραμμή.',
],
'actions_placeholder' => [
    'fi' => '- Toimenpide 1\n- Toimenpide 2',
    'sv' => '- Åtgärd 1\n- Åtgärd 2',
    'en' => '- Action 1\n- Action 2',
    'it' => '- Azione 1\n- Azione 2',
    'el' => '- Ενέργεια 1\n- Ενέργεια 2',
],
'actions_help' => [
    'fi' => 'Kirjaa konkreettiset toimenpiteet listana, yksi per rivi.',
    'sv' => 'Skriv konkreta åtgärder som lista, en per rad.',
    'en' => 'List concrete actions, one per line.',
    'it' => 'Elenca le azioni concrete, una per riga.',
    'el' => 'Καταγράψτε συγκεκριμένες ενέργειες, μία ανά γραμμή.',
],
'related_flash_label' => [
    'fi' => 'Mihin tapahtumaan tutkinta liittyy? ',
    'sv' => 'Vilken händelse gäller utredningen?',
    'en' => 'Which incident does this investigation relate to?',
    'it' => 'A quale incidente si riferisce questa indagine?',
    'el' => 'Σε ποιο περιστατικό αναφέρεται αυτή η έρευνα;',
],
'related_flash_placeholder' => [
    'fi' => 'Valitse tiedote...',
    'sv' => 'Välj meddelande...',
    'en' => 'Select flash...',
    'it' => 'Seleziona comunicazione...',
    'el' => 'Επιλέξτε ανακοίνωση...',
],
'related_flash_help' => [
    'fi' => 'Valitse ensitiedote tai vaaratilanne, jota tutkintatiedote täydentää.',
    'sv' => 'Välj den första underrättelsen eller farliga situationen som utredningsrapporten kompletterar.',
    'en' => 'Select the first release or dangerous situation that this investigation report supplements.',
    'it' => 'Seleziona il primo rilascio o la situazione pericolosa che questo rapporto di indagine integra.',
    'el' => 'Επιλέξτε την πρώτη δημοσίευση ή την επικίνδυνη κατάσταση που συμπληρώνει αυτή η έκθεση διερεύνησης.',
],
'worksite_select_placeholder' => [
    'fi' => 'Valitse työmaa.. .',
    'sv' => 'Välj arbetsplats...',
    'en' => 'Select worksite...',
    'it' => 'Seleziona cantiere...',
    'el' => 'Επιλέξτε εργοτάξιο...',
],
'step2_help' => [
    'fi' => 'Valitse työmaa, tarkempi sijainti ja tapahtuma-aika.  Tarvittaessa lisätietoja voi tarkentaa seuraavissa vaiheissa.',
    'sv' => 'Välj arbetsplats, närmare plats och tidpunkt. Vid behov kan du lägga till mer information i följande steg.',
    'en' => 'Select worksite, specific location and time. Additional details can be added in the following steps if needed.',
    'it' => 'Seleziona cantiere, posizione specifica e orario. Ulteriori dettagli possono essere aggiunti nei passaggi successivi se necessario.',
    'el' => 'Επιλέξτε εργοτάξιο, συγκεκριμένη τοποθεσία και ώρα. Επιπλέον λεπτομέρειες μπορούν να προστεθούν στα επόμενα βήματα αν χρειαστεί.',
],
'copied_from_base_placeholder' => [
    'fi' => 'Kopioidaan pohjatiedotteesta – voit muokata tarvittaessa.',
    'sv' => 'Kopieras från basmeddelandet – du kan ändra vid behov.',
    'en' => 'Copied from base flash – you can edit if needed.',
    'it' => 'Copiato dalla comunicazione base – puoi modificare se necessario.',
    'el' => 'Αντιγράφεται από τη βασική ανακοίνωση – μπορείτε να επεξεργαστείτε αν χρειαστεί.',
],
'investigation_fields_help' => [
    'fi' => 'Nämä kentät kopioidaan valitusta ensitiedotteesta/vaaratilanteesta. Voit tarkentaa, jos tiedot ovat muuttuneet.',
    'sv' => 'Dessa fält kopieras från vald första underrättelse/farlig situation.  Du kan ändra om uppgifterna har ändrats.',
    'en' => 'These fields are copied from the selected first release/dangerous situation. You can update if the information has changed.',
    'it' => 'Questi campi vengono copiati dal primo rilascio/situazione pericolosa selezionato.  Puoi aggiornare se le informazioni sono cambiate.',
    'el' => 'Αυτά τα πεδία αντιγράφονται από την επιλεγμένη πρώτη δημοσίευση/επικίνδυνη κατάσταση. Μπορείτε να ενημερώσετε αν οι πληροφορίες έχουν αλλάξει.',
],
'title_internal_label' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'title_internal_placeholder' => [
    'fi' => 'Esim. Henkilön läheltä piti -tilanne kaivoksella',
    'sv' => 'T.ex. Nära ögat-situation vid gruvan',
    'en' => 'E.g. Near miss incident at the mine',
    'it' => 'Es. Quasi incidente alla miniera',
    'el' => 'Π.χ. Παραλίγο ατύχημα στο ορυχείο',
],
'short_text_placeholder' => [
    'fi' => 'Tiivis kuvaus, joka näkyy kortin otsikkona.',
    'sv' => 'Kort beskrivning som visas som kortets rubrik.',
    'en' => 'Brief description shown as the card title.',
    'it' => 'Breve descrizione mostrata come titolo della scheda.',
    'el' => 'Σύντομη περιγραφή που εμφανίζεται ως τίτλος κάρτας.',
],
'description_placeholder' => [
    'fi' => 'Kerro tässä mitä tapahtui ja tämän hetkinen tilanne.',
    'sv' => 'Beskriv här vad som hände och nuläget.',
    'en' => 'Describe what happened and the current situation.',
    'it' => 'Descrivi cosa è successo e la situazione attuale.',
    'el' => 'Περιγράψτε τι συνέβη και την τρέχουσα κατάσταση.',
],
'root_causes_placeholder' => [
    'fi' => '- Juurisyy 1 - Juurisyy 2',
    'sv' => '- Grundorsak 1 - Grundorsak 2',
    'en' => '- Root cause 1 - Root cause 2',
    'it' => '- Causa principale 1 - Causa principale 2',
    'el' => '- Αιτία 1 - Αιτία 2',
],
'root_causes_help' => [
    'fi' => 'Kirjaa selkeästi yksi juurisyy kullekin riville.',
    'sv' => 'Skriv tydligt en grundorsak per rad.',
    'en' => 'Write one root cause per line.',
    'it' => 'Scrivi una causa principale per riga.',
    'el' => 'Γράψτε μία αιτία ανά γραμμή.',
],
'actions_placeholder' => [
    'fi' => '- Toimenpide 1 - Toimenpide 2',
    'sv' => '- Åtgärd 1 - Åtgärd 2',
    'en' => '- Action 1 - Action 2',
    'it' => '- Azione 1 - Azione 2',
    'el' => '- Ενέργεια 1 - Ενέργεια 2',
],
'actions_help' => [
    'fi' => 'Kirjaa konkreettiset toimenpiteet listana, yksi per rivi.',
    'sv' => 'Skriv konkreta åtgärder som lista, en per rad.',
    'en' => 'List concrete actions, one per line.',
    'it' => 'Elenca le azioni concrete, una per riga.',
    'el' => 'Καταγράψτε συγκεκριμένες ενέργειες, μία ανά γραμμή.',
],
'modal_translation_title' => [
    'fi' => 'Luo kieliversio',
    'en' => 'Create language version',
    'sv' => 'Skapa språkversion',
    'it' => 'Crea versione linguistica',
    'el' => 'Δημιουργία γλωσσικής έκδοσης',
],
'translation_target_lang' => [
    'fi' => 'Kohdekieli',
    'en' => 'Target language',
    'sv' => 'Målspråk',
    'it' => 'Lingua di destinazione',
    'el' => 'Γλώσσα στόχος',
],
'preview_label' => [
    'fi' => 'Esikatselu',
    'en' => 'Preview',
    'sv' => 'Förhandsgranskning',
    'it' => 'Anteprima',
    'el' => 'Προεπισκόπηση',
],
'translation_help' => [
    'fi' => 'Käännä tekstit ja paina Tallenna.  Kuvat kopioidaan automaattisesti.',
    'en' => 'Translate the texts and press Save. Images are copied automatically.',
    'sv' => 'Översätt texterna och tryck Spara.  Bilder kopieras automatiskt.',
    'it' => 'Traduci i testi e premi Salva. Le immagini vengono copiate automaticamente.',
    'el' => 'Μεταφράστε τα κείμενα και πατήστε Αποθήκευση.  Οι εικόνες αντιγράφονται αυτόματα.',
],
'btn_save_translation' => [
    'fi' => 'Tallenna kieliversio',
    'en' => 'Save language version',
    'sv' => 'Spara språkversion',
    'it' => 'Salva versione linguistica',
    'el' => 'Αποθήκευση γλωσσικής έκδοσης',
],
'short_title_label' => [
    'fi' => 'Lyhyt kuvaus',
    'en' => 'Short description',
    'sv' => 'Kort beskrivning',
    'it' => 'Breve descrizione',
    'el' => 'Σύντομη περιγραφή',
],
'description_label' => [
    'fi' => 'Kuvaus',
    'en' => 'Description',
    'sv' => 'Beskrivning',
    'it' => 'Descrizione',
    'el' => 'Περιγραφή',
],
'preview_and_save' => [
    'fi' => 'Esikatselu ja tallennus',
    'en' => 'Preview and save',
    'sv' => 'Forhandsgranska och spara',
],
'btn_back' => [
    'fi' => 'Takaisin',
    'en' => 'Back',
    'sv' => 'Tillbaka',
],
'profile_heading' => [
    'fi' => 'Oma profiili',
    'en' => 'My Profile',
],

'profile_personal_info' => [
    'fi' => 'Henkilötiedot',
    'en' => 'Personal Information',
],

'profile_role_readonly' => [
    'fi' => 'Roolia ei voi muuttaa itse. Ota yhteyttä ylläpitäjään.',
    'en' => 'Role cannot be changed. Contact administrator.',
],

'profile_worksite_heading' => [
    'fi' => 'Kotityömaa',
    'en' => 'Home Worksite',
],

'profile_worksite_help' => [
    'fi' => 'Kotityömaa suodattaa listan automaattisesti kun avaat sen.',
    'en' => 'Home worksite automatically filters the list when you open it.',
],

'profile_password_heading' => [
    'fi' => 'Vaihda salasana',
    'en' => 'Change Password',
],

'profile_current_password' => [
    'fi' => 'Nykyinen salasana',
    'en' => 'Current Password',
],

'profile_new_password' => [
    'fi' => 'Uusi salasana',
    'en' => 'New Password',
],

'profile_confirm_password' => [
    'fi' => 'Vahvista uusi salasana',
    'en' => 'Confirm New Password',
],

'profile_change_password' => [
    'fi' => 'Vaihda salasana',
    'en' => 'Change Password',
],

'profile_passwords_mismatch' => [
    'fi' => 'Salasanat eivät täsmää',
    'en' => 'Passwords do not match',
],

'notice_profile_updated' => [
    'fi' => 'Profiili päivitetty.',
    'en' => 'Profile updated.',
],

'notice_password_changed' => [
    'fi' => 'Salasana vaihdettu.',
    'en' => 'Password changed.',
],
// ===== ASETUKSET - VÄLILEHDET =====
'settings_heading' => [
    'fi' => 'Asetukset',
    'en' => 'Settings',
    'sv' => 'Inställningar',
],
'settings_tab_users' => [
    'fi' => 'Käyttäjät',
    'en' => 'Users',
    'sv' => 'Användare',
],
'settings_tab_worksites' => [
    'fi' => 'Työmaat',
    'en' => 'Worksites',
    'sv' => 'Arbetsplatser',
],
'settings_tab_audit_log' => [
    'fi' => 'Tapahtumaloki',
    'en' => 'Activity Log',
    'sv' => 'Aktivitetslogg',
],

// ===== TAPAHTUMALOKI =====
'audit_log_heading' => [
    'fi' => 'Tapahtumaloki',
    'en' => 'Activity Log',
    'sv' => 'Aktivitetslogg',
],
'audit_log_total' => [
    'fi' => 'Yhteensä',
    'en' => 'Total',
    'sv' => 'Totalt',
],
'audit_log_events' => [
    'fi' => 'tapahtumaa',
    'en' => 'events',
    'sv' => 'händelser',
],
'audit_filter_action' => [
    'fi' => 'Toiminto',
    'en' => 'Action',
    'sv' => 'Åtgärd',
],
'audit_filter_user' => [
    'fi' => 'Käyttäjä',
    'en' => 'User',
    'sv' => 'Användare',
],
'audit_filter_user_placeholder' => [
    'fi' => 'Sähköposti tai ID',
    'en' => 'Email or ID',
    'sv' => 'E-post eller ID',
],
'audit_filter_ip' => [
    'fi' => 'IP-osoite',
    'en' => 'IP Address',
    'sv' => 'IP-adress',
],
'audit_col_time' => [
    'fi' => 'Aika',
    'en' => 'Time',
    'sv' => 'Tid',
],
'audit_col_user' => [
    'fi' => 'Käyttäjä',
    'en' => 'User',
    'sv' => 'Användare',
],
'audit_col_action' => [
    'fi' => 'Toiminto',
    'en' => 'Action',
    'sv' => 'Åtgärd',
],
'audit_col_target' => [
    'fi' => 'Kohde',
    'en' => 'Target',
    'sv' => 'Mål',
],
'audit_col_ip' => [
    'fi' => 'IP',
    'en' => 'IP',
    'sv' => 'IP',
],
'audit_col_details' => [
    'fi' => 'Tiedot',
    'en' => 'Details',
    'sv' => 'Detaljer',
],
'audit_no_results' => [
    'fi' => 'Ei tapahtumia',
    'en' => 'No events',
    'sv' => 'Inga händelser',
],
'audit_details_title' => [
    'fi' => 'Lisätiedot',
    'en' => 'Details',
    'sv' => 'Detaljer',
],

// ===== SIVUTUS =====
'pagination_prev' => [
    'fi' => 'Edellinen',
    'en' => 'Previous',
    'sv' => 'Föregående',
],
'pagination_next' => [
    'fi' => 'Seuraava',
    'en' => 'Next',
    'sv' => 'Nästa',
],
'pagination_page' => [
    'fi' => 'Sivu',
    'en' => 'Page',
    'sv' => 'Sida',
],

// ===== YLEISET NAPIT =====
'btn_close' => [
    'fi' => 'Sulje',
    'en' => 'Close',
    'sv' => 'Stäng',
],
'filter_all' => [
    'fi' => 'Kaikki',
    'en' => 'All',
    'sv' => 'Alla',
],
'filter_apply' => [
    'fi' => 'Suodata',
    'en' => 'Filter',
    'sv' => 'Filtrera',
],
'filter_clear' => [
    'fi' => 'Tyhjennä',
    'en' => 'Clear',
    'sv' => 'Rensa',
],
'filter_date_from' => [
    'fi' => 'Alkaen',
    'en' => 'From',
    'sv' => 'Från',
],
'filter_date_to' => [
    'fi' => 'Päättyen',
    'en' => 'To',
    'sv' => 'Till',
],
// Kuvapankki - Asetukset
'settings_tab_image_library' => [
    'fi' => 'Kuvapankki',
    'en' => 'Image Library',
],
'settings_image_library_heading' => [
    'fi' => 'Kuvapankin hallinta',
    'en' => 'Image Library Management',
],
'settings_image_library_help' => [
    'fi' => 'Lisää kuvia, joita käyttäjät voivat valita tiedotteisiin. Esimerkiksi hahmokuvia loukkaantumiskohtien merkintään.',
    'en' => 'Add images that users can select for bulletins. For example, body figures for marking injury locations.',
],
'library_upload_heading' => [
    'fi' => 'Lisää uusi kuva',
    'en' => 'Add new image',
],
'library_label_image' => [
    'fi' => 'Kuvatiedosto',
    'en' => 'Image file',
],
'library_label_title' => [
    'fi' => 'Otsikko',
    'en' => 'Title',
],
'library_label_category' => [
    'fi' => 'Kategoria',
    'en' => 'Category',
],
'library_label_description' => [
    'fi' => 'Kuvaus (valinnainen)',
    'en' => 'Description (optional)',
],
// ===== KUVAPANKKI - KATEGORIAT =====
'library_cat_all' => [
    'fi' => 'Kaikki',
    'en' => 'All',
    'sv' => 'Alla',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'library_cat_body' => [
    'fi' => 'Hahmokuvat',
    'en' => 'Body figures',
    'sv' => 'Kroppsfigurer',
    'it' => 'Figure del corpo',
    'el' => 'Σχήματα σώματος',
],
'library_cat_warning' => [
    'fi' => 'Varoitusmerkit',
    'en' => 'Warning signs',
    'sv' => 'Varningsskyltar',
    'it' => 'Segnali di avvertimento',
    'el' => 'Προειδοποιητικά σήματα',
],
'library_cat_equipment' => [
    'fi' => 'Laitteet',
    'en' => 'Equipment',
    'sv' => 'Utrustning',
    'it' => 'Attrezzature',
    'el' => 'Εξοπλισμός',
],
'library_cat_template' => [
    'fi' => 'Pohjat',
    'en' => 'Templates',
    'sv' => 'Mallar',
    'it' => 'Modelli',
    'el' => 'Πρότυπα',
],

// ===== KUVAPANKKI - FORMISSA =====
'image_library_btn' => [
    'fi' => 'Valitse kuvapankista',
    'en' => 'Choose from library',
    'sv' => 'Välj från bildbibliotek',
    'it' => 'Scegli dalla libreria',
    'el' => 'Επιλέξτε από τη βιβλιοθήκη',
],
'image_library_help' => [
    'fi' => 'Valitse valmis hahmokuva tai pohja, johon voit lisätä merkintöjä.',
    'en' => 'Choose a ready-made figure or template to add annotations.',
    'sv' => 'Välj en färdig figur eller mall att lägga till markeringar på.',
    'it' => 'Scegli una figura o un modello pronto per aggiungere annotazioni.',
    'el' => 'Επιλέξτε μια έτοιμη φιγούρα ή πρότυπο για να προσθέσετε σημειώσεις.',
],
'image_library_title' => [
    'fi' => 'Kuvapankki',
    'en' => 'Image Library',
    'sv' => 'Bildbibliotek',
    'it' => 'Libreria immagini',
    'el' => 'Βιβλιοθήκη εικόνων',
],
'library_select_btn' => [
    'fi' => 'Valitse kuva',
    'en' => 'Select image',
    'sv' => 'Välj bild',
    'it' => 'Seleziona immagine',
    'el' => 'Επιλέξτε εικόνα',
],
'library_no_images' => [
    'fi' => 'Ei kuvia tässä kategoriassa.',
    'en' => 'No images in this category.',
    'sv' => 'Inga bilder i denna kategori.',
    'it' => 'Nessuna immagine in questa categoria.',
    'el' => 'Δεν υπάρχουν εικόνες σε αυτή την κατηγορία.',
],
'library_loading' => [
    'fi' => 'Ladataan kuvia...',
    'en' => 'Loading images...',
    'sv' => 'Laddar bilder...',
    'it' => 'Caricamento immagini...',
    'el' => 'Φόρτωση εικόνων...',
],
// ===== AUDIT LOG TOIMINNOT =====
'flash_comment' => [
    'fi' => 'Kommentti lisätty',
    'en' => 'Comment added',
    'sv' => 'Kommentar tillagd',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'flash_create' => [
    'fi' => 'Tiedote luotu',
    'en' => 'Flash created',
    'sv' => 'Meddelande skapat',
    'it' => 'Comunicazione creata',
    'el' => 'Ανακοίνωση δημιουργήθηκε',
],
'flash_edit' => [
    'fi' => 'Tiedote muokattu',
    'en' => 'Flash edited',
    'sv' => 'Meddelande redigerat',
    'it' => 'Comunicazione modificata',
    'el' => 'Ανακοίνωση επεξεργάστηκε',
],
'flash_delete' => [
    'fi' => 'Tiedote poistettu',
    'en' => 'Flash deleted',
    'sv' => 'Meddelande borttaget',
    'it' => 'Comunicazione eliminata',
    'el' => 'Ανακοίνωση διαγράφηκε',
],
'flash_bulk_delete' => [
    'fi' => 'Useita tiedotteita poistettu',
    'en' => 'Multiple flashes deleted',
    'sv' => 'Flera meddelanden borttagna',
    'it' => 'Più comunicazioni eliminate',
    'el' => 'Πολλαπλές ανακοινώσεις διαγράφηκαν',
],
'flash_status_change' => [
    'fi' => 'Tilan muutos',
    'en' => 'Status changed',
    'sv' => 'Status ändrad',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'flash_send_review' => [
    'fi' => 'Lähetetty tarkistettavaksi',
    'en' => 'Sent for review',
    'sv' => 'Skickat för granskning',
    'it' => 'Inviato per revisione',
    'el' => 'Στάλθηκε για έλεγχο',
],
'flash_send_comms' => [
    'fi' => 'Lähetetty viestintään',
    'en' => 'Sent to communications',
    'sv' => 'Skickat till kommunikation',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στο τμήμα επικοινωνίας',
],
'flash_publish' => [
    'fi' => 'Tiedote julkaistu',
    'en' => 'Flash published',
    'sv' => 'Meddelande publicerat',
    'it' => 'Comunicazione pubblicata',
    'el' => 'Ανακοίνωση δημοσιεύτηκε',
],
'flash_info_request' => [
    'fi' => 'Lisätietoja pyydetty',
    'en' => 'Information requested',
    'sv' => 'Mer information begärd',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'login' => [
    'fi' => 'Kirjautuminen',
    'en' => 'Login',
    'sv' => 'Inloggning',
    'it' => 'Accesso',
    'el' => 'Σύνδεση',
],
'login_failed' => [
    'fi' => 'Kirjautuminen epäonnistui',
    'en' => 'Login failed',
    'sv' => 'Inloggning misslyckades',
    'it' => 'Accesso fallito',
    'el' => 'Η σύνδεση απέτυχε',
],
'logout' => [
    'fi' => 'Uloskirjautuminen',
    'en' => 'Logout',
    'sv' => 'Utloggning',
    'it' => 'Disconnessione',
    'el' => 'Αποσύνδεση',
],
'user_create' => [
    'fi' => 'Käyttäjä luotu',
    'en' => 'User created',
    'sv' => 'Användare skapad',
    'it' => 'Utente creato',
    'el' => 'Χρήστης δημιουργήθηκε',
],
'user_update' => [
    'fi' => 'Käyttäjä päivitetty',
    'en' => 'User updated',
    'sv' => 'Användare uppdaterad',
    'it' => 'Utente aggiornato',
    'el' => 'Χρήστης ενημερώθηκε',
],
'user_delete' => [
    'fi' => 'Käyttäjä poistettu',
    'en' => 'User deleted',
    'sv' => 'Användare borttagen',
    'it' => 'Utente eliminato',
    'el' => 'Χρήστης διαγράφηκε',
],
'password_reset' => [
    'fi' => 'Salasana nollattu',
    'en' => 'Password reset',
    'sv' => 'Lösenord återställt',
    'it' => 'Password reimpostata',
    'el' => 'Επαναφορά κωδικού',
],
// ===== AUDIT LOG - LISÄÄ PUUTTUVAT =====
'flash_update' => [
    'fi' => 'Tiedote päivitetty',
    'en' => 'Flash updated',
    'sv' => 'Meddelande uppdaterat',
    'it' => 'Comunicazione aggiornata',
    'el' => 'Ανακοίνωση ενημερώθηκε',
],
'flash_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'en' => 'Sent to communications',
    'sv' => 'Skickat till kommunikation',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στο τμήμα επικοινωνίας',
],
'user_password_reset' => [
    'fi' => 'Salasana nollattu',
    'en' => 'Password reset',
    'sv' => 'Lösenord återställt',
    'it' => 'Password reimpostata',
    'el' => 'Επαναφορά κωδικού',
],
'profile_update' => [
    'fi' => 'Profiili päivitetty',
    'en' => 'Profile updated',
    'sv' => 'Profil uppdaterad',
    'it' => 'Profilo aggiornato',
    'el' => 'Προφίλ ενημερώθηκε',
],
'password_change' => [
    'fi' => 'Salasana vaihdettu',
    'en' => 'Password changed',
    'sv' => 'Lösenord ändrat',
    'it' => 'Password modificata',
    'el' => 'Ο κωδικός άλλαξε',
],
'worksite_create' => [
    'fi' => 'Työmaa luotu',
    'en' => 'Worksite created',
    'sv' => 'Arbetsplats skapad',
    'it' => 'Cantiere creato',
    'el' => 'Εργοτάξιο δημιουργήθηκε',
],
'worksite_update' => [
    'fi' => 'Työmaa päivitetty',
    'en' => 'Worksite updated',
    'sv' => 'Arbetsplats uppdaterad',
    'it' => 'Cantiere aggiornato',
    'el' => 'Εργοτάξιο ενημερώθηκε',
],
'worksite_delete' => [
    'fi' => 'Työmaa poistettu',
    'en' => 'Worksite deleted',
    'sv' => 'Arbetsplats borttagen',
    'it' => 'Cantiere eliminato',
    'el' => 'Εργοτάξιο διαγράφηκε',
],
'settings_update' => [
    'fi' => 'Asetukset päivitetty',
    'en' => 'Settings updated',
    'sv' => 'Inställningar uppdaterade',
    'it' => 'Impostazioni aggiornate',
    'el' => 'Ρυθμίσεις ενημερώθηκαν',
],
'image_library_add' => [
    'fi' => 'Kuva lisätty kuvapankkiin',
    'en' => 'Image added to library',
    'sv' => 'Bild tillagd i bildbibliotek',
    'it' => 'Immagine aggiunta alla libreria',
    'el' => 'Εικόνα προστέθηκε στη βιβλιοθήκη',
],
'image_library_delete' => [
    'fi' => 'Kuva poistettu kuvapankista',
    'en' => 'Image deleted from library',
    'sv' => 'Bild borttagen från bildbibliotek',
    'it' => 'Immagine eliminata dalla libreria',
    'el' => 'Εικόνα διαγράφηκε από τη βιβλιοθήκη',
],
'image_library_toggle' => [
    'fi' => 'Kuvan näkyvyys muutettu',
    'en' => 'Image visibility changed',
    'sv' => 'Bildens synlighet ändrad',
    'it' => 'Visibilità immagine modificata',
    'el' => 'Η ορατότητα εικόνας άλλαξε',
],
// --- VAHVISTUSMODAALI ---
'confirm_submit_title' => [
    'fi' => 'Vahvista lähetys',
    'sv' => 'Bekräfta sändning',
    'en' => 'Confirm submission',
    'it' => 'Conferma invio',
    'el' => 'Επιβεβαίωση υποβολής',
],
'confirm_submit_text' => [
    'fi' => 'Oletko varma, että haluat lähettää tiedotteen tarkistettavaksi?',
    'sv' => 'Är du säker på att du vill skicka meddelandet för granskning?',
    'en' => 'Are you sure you want to send this flash for review?',
    'it' => 'Sei sicuro di voler inviare questa comunicazione per la revisione?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να στείλετε αυτή την ανακοίνωση για έλεγχο;',
],
'confirm_submit_help' => [
    'fi' => 'Tiedotetta voi vielä muokata ennen julkaisua.',
    'sv' => 'Meddelandet kan fortfarande redigeras innan publicering.',
    'en' => 'The flash can still be edited before publishing.',
    'it' => 'La comunicazione può ancora essere modificata prima della pubblicazione.',
    'el' => 'Η ανακοίνωση μπορεί ακόμα να επεξεργαστεί πριν τη δημοσίευση.',
],
'btn_confirm_yes' => [
    'fi' => 'Kyllä, lähetä',
    'sv' => 'Ja, skicka',
    'en' => 'Yes, send',
    'it' => 'Sì, invia',
    'el' => 'Ναι, αποστολή',
],
'two_slides_notice_title' => [
    'fi' => 'Sisältö jaetaan kahdelle kortille',
    'sv' => 'Innehållet delas på två kort',
    'en' => 'Content will be split into two cards',
    'it' => 'Il contenuto sarà diviso in due schede',
    'el' => 'Το περιεχόμενο θα χωριστεί σε δύο κάρτες',
],
'two_slides_notice_text' => [
    'fi' => 'Tekstin määrän vuoksi tiedote näytetään kahdella dialla: yhteenveto ja juurisyyt/toimenpiteet.',
    'sv' => 'På grund av textmängden visas meddelandet på två bilder: sammanfattning och grundorsaker/åtgärder.',
    'en' => 'Due to the amount of text, the flash will be displayed on two slides: summary and root causes/actions.',
    'it' => 'A causa della quantità di testo, la comunicazione verrà visualizzata su due diapositive.',
    'el' => 'Λόγω του όγκου κειμένου, η ανακοίνωση θα εμφανιστεί σε δύο διαφάνειες.',
],
// Audit log -toimintojen käännökset
'login_success' => [
    'fi' => 'Kirjautuminen onnistui',
    'sv' => 'Inloggning lyckades',
    'en' => 'Login successful',
    'it' => 'Accesso riuscito',
    'el' => 'Επιτυχής σύνδεση',
],
'login_failed' => [
    'fi' => 'Kirjautuminen epäonnistui',
    'sv' => 'Inloggning misslyckades',
    'en' => 'Login failed',
    'it' => 'Accesso fallito',
    'el' => 'Αποτυχία σύνδεσης',
],
'logout' => [
    'fi' => 'Uloskirjautuminen',
    'sv' => 'Utloggning',
    'en' => 'Logout',
    'it' => 'Disconnessione',
    'el' => 'Αποσύνδεση',
],
'flash_create' => [
    'fi' => 'Safetyflash luotu',
    'sv' => 'Safetyflash skapad',
    'en' => 'Safetyflash created',
    'it' => 'Safetyflash creato',
    'el' => 'Δημιουργήθηκε Safetyflash',
],
'flash_update' => [
    'fi' => 'Safetyflash muokattu',
    'sv' => 'Safetyflash uppdaterad',
    'en' => 'Safetyflash updated',
    'it' => 'Safetyflash aggiornato',
    'el' => 'Ενημερώθηκε Safetyflash',
],
'flash_delete' => [
    'fi' => 'Safetyflash poistettu',
    'sv' => 'Safetyflash raderad',
    'en' => 'Safetyflash deleted',
    'it' => 'Safetyflash eliminato',
    'el' => 'Διαγράφηκε Safetyflash',
],
'flash_bulk_delete' => [
    'fi' => 'Useita safetyflasheja poistettu',
    'sv' => 'Flera safetyflash raderade',
    'en' => 'Multiple safetyflashes deleted',
    'it' => 'Più safetyflash eliminati',
    'el' => 'Διαγράφηκαν πολλά Safetyflash',
],
'flash_comment' => [
    'fi' => 'Kommentti lisätty',
    'sv' => 'Kommentar tillagd',
    'en' => 'Comment added',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'flash_publish' => [
    'fi' => 'Safetyflash julkaistu',
    'sv' => 'Safetyflash publicerad',
    'en' => 'Safetyflash published',
    'it' => 'Safetyflash pubblicato',
    'el' => 'Δημοσιεύτηκε Safetyflash',
],
'user_not_found' => [
    'fi' => 'Käyttäjää ei löytynyt',
    'sv' => 'Användaren hittades inte',
    'en' => 'User not found',
    'it' => 'Utente non trovato',
    'el' => 'Ο χρήστης δεν βρέθηκε',
],
'inactive' => [
    'fi' => 'Käyttäjä ei ole aktiivinen',
    'sv' => 'Användaren är inte aktiv',
    'en' => 'User is not active',
    'it' => 'Utente non attivo',
    'el' => 'Ο χρήστης δεν είναι ενεργός',
],
'wrong_password' => [
    'fi' => 'Väärä salasana',
    'sv' => 'Fel lösenord',
    'en' => 'Wrong password',
    'it' => 'Password errata',
    'el' => 'Λάθος κωδικός',
],
'notice_worksite_activated' => [
    'fi' => 'Työmaa aktivoitu.',
    'sv' => 'Arbetsplats aktiverad.',
    'en' => 'Worksite activated.',
    'it' => 'Cantiere attivato.',
    'el' => 'Το εργοτάξιο ενεργοποιήθηκε.',
],

'notice_worksite_deactivated' => [
    'fi' => 'Työmaa passivoitu.',
    'sv' => 'Arbetsplats inaktiverad.',
    'en' => 'Worksite deactivated.',
    'it' => 'Cantiere disattivato.',
    'el' => 'Το εργοτάξιο απενεργοποιήθηκε.',
],

'audit_worksite_activated' => [
    'fi' => 'Työmaa aktivoitu',
    'sv' => 'Arbetsplats aktiverad',
    'en' => 'Worksite activated',
    'it' => 'Cantiere attivato',
    'el' => 'Ενεργοποίηση εργοταξίου',
],

'audit_worksite_deactivated' => [
    'fi' => 'Työmaa passivoitu',
    'sv' => 'Arbetsplats inaktiverad',
    'en' => 'Worksite deactivated',
    'it' => 'Cantiere disattivato',
    'el' => 'Απενεργοποίηση εργοταξίου',
],
'worksite_added' => [
  'fi' => 'Työmaa lisätty.',
  'sv' => 'Arbetsplats tillagd.',
  'en' => 'Worksite added.',
  'it' => 'Cantiere aggiunto.',
  'el' => 'Το εργοτάξιο προστέθηκε.',
],
'worksite_enabled' => [
  'fi' => 'Työmaa aktivoitu.',
  'sv' => 'Arbetsplats aktiverad.',
  'en' => 'Worksite activated.',
  'it' => 'Cantiere attivato.',
  'el' => 'Το εργοτάξιο ενεργοποιήθηκε.',
],
'worksite_disabled' => [
  'fi' => 'Työmaa passivoitu.',
  'sv' => 'Arbetsplats inaktiverad.',
  'en' => 'Worksite deactivated.',
  'it' => 'Cantiere disattivato.',
  'el' => 'Το εργοτάξιο απενεργοποιήθηκε.',
],
'notice_image_added' => [
    'fi' => 'Kuva lisätty kuvapankkiin.',
    'sv' => 'Bild tillagd i bildbibliotek.',
    'en' => 'Image added to library.',
    'it' => 'Immagine aggiunta alla libreria.',
    'el' => 'Εικόνα προστέθηκε στη βιβλιοθήκη.',
],
'notice_image_deleted' => [
    'fi' => 'Kuva poistettu kuvapankista.',
    'sv' => 'Bild borttagen från bildbibliotek.',
    'en' => 'Image deleted from library.',
    'it' => 'Immagine eliminata dalla libreria.',
    'el' => 'Εικόνα διαγράφηκε από τη βιβλιοθήκη.',
],
'notice_image_toggled' => [
    'fi' => 'Kuvan näkyvyys muutettu.',
    'sv' => 'Bildens synlighet ändrad.',
    'en' => 'Image visibility changed.',
    'it' => 'Visibilità immagine modificata.',
    'el' => 'Η ορατότητα της εικόνας άλλαξε.',
],

    ], // sulkee 'terms' arrayn
]; // sulkee pää-arrayn